management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all endpoints
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      ## AUTH 서버 라우팅
      routes[0]:
        id: auth
        uri: lb://auth
        predicates[0]: Path=/api/users/**
      ## SNS 서버 라우팅
      routes[1]:
        id: sns
        uri: lb://sns
        predicates[0]: Path=/api/sns/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3090'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS






