app:
  jwt:
    accessTokenValidMS: 3600000
    refreshTokenValidMS: 604800000
    secret: ${APP_JWT_SECRET}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: ${SCONNECT_REDIS_HOST}   # Redis host
    port: ${SCONNECT_REDIS_PORT}   # Redis port
server:
    port: 8081

