spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sns_db
    username: root
    password: urnotyelping00
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB