spring:
  application:
    name: sns
  datasource:
    url: jdbc:mysql://localhost:3306/sns_db
    username: root
    password: urnotyelping00
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: auth
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

server:
  port: 8082

cloud:
  aws:
    region:
      static: us-east-1 #TODO: aws s3에 맞게 변경
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
